### ISSUE TITLE
Flags are parsed as signed in the C Python extension.

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1027]
`tables.nodes.flags` and `tables.individuals.flags` are listed as dtype `np.uint32`. But it looks like the C library is expecting them to be set as signed 32 bit ints instead:

```
ts = msprime.simulate(4, mutation_rate=10)
tables = ts.dump_tables()
tables.nodes.add_row(flags = np.iinfo(np.int32).max)  # works
tables.nodes.add_row(flags = np.iinfo(np.uint32).max)  # fails with "OverflowError: signed integer is greater than maximum"
tables.individuals.add_row(flags = np.iinfo(np.int32).max)  # works
tables.individuals.add_row(flags = np.iinfo(np.uint32).max)  # fails with "OverflowError: signed integer is greater than maximum"
```

**Comment by hyanwong** [comment]
I suspect this is a trivial fix @benjeffery - could we get it into the upcoming release?

**Comment by benjeffery** [comment]
We're using `i` for `flags` in `PyArg_ParseTupleAndKeywords`. I guess that should be `I` but then we would need to implement our own overflow checking as `I` has none.

**Comment by hyanwong** [comment]
> then we would need to implement our own overflow checking as `I` has none.

Hmm, that's a pain, and a bit of an oversight in the C-interface lib.

**Comment by jeromekelleher** [comment]
This is a bug all right, we should probably be using "I". I'm not sure about the overflow checking. I guess we could use "K" so that we can be sure the value is a uint64_t, and then check if the value is > UINT32_MAX. I really wish python would implement letter codes for ``uint32_t`` etc, it would make life a lot easier.

I guess it is an easily made bug to have an overflow (i.e., ``flags=1<<32``), so we should do this. Maybe we should use the "O&" form, and define a "uint32_converter" function to check this rigorously?

**Comment by benjeffery** [comment]
I don't think `K` will be water-tight as that has no overflow checking - negatives would be silently cast. I think using `L` and then checking `<= UINT32_MAX` and `> 0`is water-tight.
