### ISSUE TITLE
Allow split_polytomies() to take an rng, not just a seed

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1096]
If we are only providing the ability to split polytomies per tree, rather than over the entire ts, then it's a pain to have to produce a different random_seed for each tree along a tree sequence. We should be able to provide *either* a seed *or* an rng object.

I'm not sure if the parameter should still be called `random_seed` in this case, but I guess it can be retained for backwards compatibility (and consistency with other methods). I guess we could roll this out to any other tskit methods that take a random_seed too (that might only be `random_binary_tree`), but since those are not usually performed on multiple trees in a TS, this would only be for consistency.

**Comment by jeromekelleher** [comment]
I don't think we want to do this because it places an API dependency on whatever RNG class we use, which would break if we ever implement this in C.

Generating an array of seeds per tree using numpy isn't a big deal, I think. You'd have to do this anyway if you wanted to do stuff in parallel (an RNG instance would only get in the way).

**Comment by hyanwong** [comment]
Hmm, both good points. I guess this might be solved if we ever do want to implement a per-tree-seq polytomy breaking routine (which I know you are against, but would save me days (perhaps weeks) of computation time for what I'm doing at the moment).
