### ISSUE TITLE
Make edge_diffs reversible

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1286]
It would be nice, although probably hard work, to make the `edge_diffs()` method reversible, or even have `.prev` and `.next` functionality, like we have for `.trees()`. But I suspect I am the main user of the `edge_diffs`, so this isn't high priority, and can get booted into the "nice to have" category. Perhaps it should be considered as part of https://github.com/tskit-dev/tskit/projects/5 ?

**Comment by jeromekelleher** [comment]
This would require a fair bit of plumbing I'm afraid and wouldn't be terribly straightforward.

There's a question about whether we should bother doing this in C any more though - if we implemented edge_diffs in Python instead it would be much more straightforward. Not that hard now we have direct access to the indexes. I doubt performance would be affected much, since by definition we're doing stuff in Python anyway.

Do we actually use the C edge diffs much?

**Comment by hyanwong** [comment]
Having glanced at the C code I thought that might be the case. Re the C edge_diffs, I never touch the C API, so I'm afraid I'm not the right person to ask.

For me, a common idiom is to iterate over both the tree and the edge diffs at the same time, i.e. `zip(ts.trees(), ts.edge_diffs())`. So there's an (rather weak) argument that the `trees()` iterator should have a switch to allow a `Tree` to to access its edge diffs, just like you can switch on the `sample_lists` functionality. On reflection, I think it's probably overloading the `trees()` method with too much functionality, but I mention it here in case it sparks off any other ideas in this area.

**Comment by benjeffery** [comment]
Seems we don't have a concrete plan to do this, so I'll put it in "future" for now.
