### ISSUE TITLE
Change `tsk_tree_t.left/right` to an interval.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#1686]
Marked as a TODO in current code.

**Comment by jeromekelleher** [comment]
I wouldn't be too dogmatic about this one - let's see how much code it would break in the test suite. If it's a lot, then maybe not worth it.

**Comment by jeromekelleher** [comment]
Perhaps the right thing to do here is to add an anonymous struct to the tree class, so that we write things like ``tree.interval.left`` rather than ``tree.left``. This seems easier to understand, but is perhaps extraneous? I think ``tree.interval.left`` is easier to read than ``tree.interval[0]``, if we were to use an ``double interval[2]`` for the interval.

**Comment by hyanwong** [comment]
FWIW `tree.interval.left` matches the python API.
