### ISSUE TITLE
Extra methods for the Variant class

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2193]
Just chatting to @szhan, and we thought of some extra methods for the Variant class. Some are simple: e.g. you might want to calculate the frequency of all the alleles (accounting for multiple mutations, missing data, etc). The one we are thinking about is the imputation quality score (IQS), which I could imagine being calculated like this:

```
total_IQS = 0
for variant1, variant2 in zip(ts_with_missing.variants(), ts_imputed.variants()):
     total_IQS += variant1.imputation_quality_score(variant2)
```

**Comment by szhan** [comment]
We should also considering adding functions to compute concordance rate (which is calculated to get the IQS anyway) and squared correlation.

**Comment by benjeffery** [comment]
Sounds like a useful thing to have - although I think ee need to think through where this is best placed in the API. For example this method could be placed on the `Site` class.

I assume `imputation_quality_score` makes no sense if the samples are different between the two variants? If so we need to think about how we would detect that?

**Comment by hyanwong** [comment]
> I assume imputation_quality_score makes no sense if the samples are different between the two variants? If so we need to think about how we would detect that?

Yes, that's a good point. Presumably we have to do this when doing `ts.coiterate`, so there's a call for a general method to check if 2 tree sequences are describing the same data (presumably e.g. you might want to check that they have the same sequence length)

**Comment by jeromekelleher** [comment]
This seems like a useful method. We could do some basic checks like whether the size of the genotypes arrays match and just state as documentation that it's up to the user to make sure the operation makes sense (I think this is a case of "trying to stop people doing stupid things will also stop people doing clever things").

These are generally methods of the variant class I think, because we don't want to have to call "decode" ourselves etc.

Can we open specific issues for the variant metrics we want to compute? I expect we'll implement most of these using numpy, but we could consider putting them into the C API.

**Comment by benjeffery** [comment]
Yes, @hyanwong can you go ahead and open the specific methods and close this when you have? Thanks!

**Comment by szhan** [comment]
Issue #2198 about comparing two tree sequences is relevant.

**Comment by szhan** [comment]
I'm creating separate issues for the specific methods.

**Comment by jeromekelleher** [comment]
Great - let's close this now then. Can reopen if there's other things to discuss.
