### ISSUE TITLE
Inconsistent mutations error when reading variant from SLiM addNewDrawnMutation

### ISSUE THREAD

**Issue by deboraycb** [tskit-dev/tskit#2195]
Hello tskit team,

I am reading a tree sequence file generated in SLiM and I get this error when I loop over ts.variants():
`Inconsistent mutations: state already equal to derived state`

If I loop over ts.sites(), I get no error.
I am printing out all variant positions and I notice the error appears whenever I get to a variant that was included with the following SLiM code:

```
initializeMutationTypeNuc("m2", d2, "f", Sbs)
```
...
```
targetBS = sample(p0.genomes,1);
AncNuc = targetBS.nucleotides(start=asInteger(L/2), end=asInteger(L/2)); // middle of sequence
cat('// The ancestral nucleotide at the center is '+AncNuc+'\n');
NewNuc=c();
for(n in c("A","T","C","G")){
    if(n != AncNuc){
      NewNuc = c(NewNuc,n);
    }
}
targetBS.addNewDrawnMutation(m2,asInteger(L/2),nucleotide=NewNuc);
```

This seems related to this issue https://github.com/MesserLab/SLiM/issues/64, but it's not exactly the same because I am not sampling positions for the mutations that are out of order.
Also feels like it's related to this issue https://github.com/tskit-dev/msprime/pull/1434 but I still couldn't figure out what to do based on it.

I am attaching here the tree sequence file and a minimal example of python code that shows the error in tskit:
[variants_loop_minex.py.gz](https://github.com/tskit-dev/msprime/files/8477268/variants_loop_minex.py.gz)
[slim_26345_BS.ts.gz](https://github.com/tskit-dev/msprime/files/8477270/slim_26345_BS.ts.gz)

Please let me know if there is anything else I can provide to help understand what is going on.

Thanks!

**Comment by jeromekelleher** [comment]
Hi @deboraycb :wave:

No worries on opening the issue in the msprime repo, it's easy for us to transfer. I've moved the issue here to tskit.

@bhaller - any thoughts on what's going on here? Is this a tskit issue/SLiM issue/neither?

**Comment by bhaller** [comment]
Hmm.  Tagging @petrelharp as well.

Is this `Inconsistent mutations: state already equal to derived state` error a new error?  I.e., have you guys recently adding this check, where previously the code did not do this check?

I believe there are cases where SLiM can indeed record a derived state that is identical to the previous state.  It would take a bit of digging to find those cases, but I recall that they do exist.  It's not ideal, of course, but they are difficult to eliminate in some edge situations without a lot of work (and perhaps slowing down the algorithm in question), and they seemed harmless at the time.  They have not been a problem before, in general, which is why I wonder whether this error message is a relatively new introduction to tskit, or has broadened in its application in some way.

We had a very similar issue that got dealt with here:

https://github.com/MesserLab/SLiM/issues/195

In the discussion of that issue, @petrelharp says that "tskit now allows silent mutations (ie, mutations that don't change state)" and that such silent mutations "won't be a problem with the updated tskit".  What happened to that?  From the discussion in SLiM 195 (link above) it sounds like we specifically decided not to worry about such cases, when difficult to fix, because we expected that tskit would not treat them as an error.

It seems to me that we need to make a decision regarding policy here.  I think @petrelharp and I were under the impression that such silent mutations were not considered to be an error, but tskit is now apparently flagging them as an error for @deboraycb.  Do we want them to be an error or not?  I kinda vote for "not", partly, I will admit, out of laziness – I just don't want to delve into the bowels of SLiM's tree-sequence recording to try to find and fix every edge case where this can occur, as I feel like I have other things I would rather do with my time.  :->  But if there is a strong argument for having them be considered an error, then I guess that's what @petrelharp and I will have to do.

A side question for @deboraycb: what versions of SLiM, msprime, tskit, and pyslim are you using?  Could this error just be coming from a tskit that is out of date, and this check has, in fact, been removed in the current tskit?

**Comment by bhaller** [comment]
OK, I'm relieved to hear that this situation is legal now, whew.  :->

Well, if incompatible software versions is likely to be the problem, it's probably not worth debugging the details of it.  Let's just recommend that @deboraycb go scorched-earth, right?  Uninstall SLiM, tskit, msprime, and pyslim, and then install current versions of all to ensure that she has a compatible software stack?

**Comment by deboraycb** [comment]
ah, I updated to slim 3.7 and the error is gone! (I had 3.6 before)
Thanks for the super quick and helpful replies!
