### ISSUE TITLE
Check whether two tree sequences contain the same set of samples

### ISSUE THREAD

**Issue by szhan** [tskit-dev/tskit#2201]
A function in the TreeSequence class to perform this check should help us to determine whether two tree sequences are comparable (#2198) and to calculate imputation performance metrics for each site (#2193).

**Comment by jeromekelleher** [comment]
I don't know how we'd do this tbh - beyond having the same number of samples, how do we verify identity? @hyanwong - do you have ideas here? If it comes down to metadata etc, I suspect we'd end up spending more time fiddling with metadata in order to get the check to pass on things that we want to compare than we'd save from mistakenly comparing things that we didn't mean to.

**Comment by benjeffery** [comment]
Ah, I saw #2198 first. As I said there I think the only way might be to check a single metadata key (which is passed as an argument), but even then I'm not sure this is a job for the tskit API as it is very simple to do in client code.

**Comment by jeromekelleher** [comment]
I think we're better off doing input checking on a case-by-case basis for specific methods rather than trying to come up with some general definition of compatibility. So, I'd vote for closing this and #2198 .
