### ISSUE TITLE
write segregating sites and Tajima's D functions

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#230]
The branch length version of segregating sites is total branch length, which we also want.

**Comment by jeromekelleher** [comment]
What do we want to call this? Calling ``ts.segregating_sites(mode="branch")`` to get the total branch length feels bad. Maybe we should just have two methods, one for sites and one for branch_length?

**Comment by petrelharp** [comment]
This was also bothering me. I think that just calling it "segregating sites" is the right way forward, though, because (a) we can provide a lookup  table #231 and (b) our convention so far is to name statistics after their "site" version. Which is sensible, I think. I've got some others' input, who agreed.

**Comment by jeromekelleher** [comment]
Question: should the function be ``Tajimas_D`` or ``tajimas_D``? I think it should probably be the latter, as all other functions are lowercase, except for things like ``Fst``, ``Y2`` etc. These seem like reasonable exceptions since it's following standard notation. Capitalising Tajima seems less obviously like the right thing to do for me --- consistency is good for users.

Not a strong opinion though.

**Comment by petrelharp** [comment]
>  except for things like Fst
I wondered about this also; but Tajima is definately capitalised; I'd think it would fall under the category of "things like Fst". Either is OK with me, but I'd vote to keep it capitalised.

**Comment by jeromekelleher** [comment]
OK, let's keep it as Tajimas_D then.

**Comment by jeromekelleher** [comment]
Closed in #237
