### ISSUE TITLE
Don't return array-types for 1x1 statistics?

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#2308]
By default, these statistics are returned as arrays with dimension `()`
```
 >>> div = ts.diversity()
>>> div.shape
()
```
This is annoying because you have to do something like `div[()]` to access the value (not `div[0]`, which is a tiny bit more intuitive at least). I think it would be better to just return the scalar value itself in this situation.

**Comment by petrelharp** [comment]
Hah, I was just having to look up how to un-array-ify this exact thing (since you can't `json.dump( )` a numpy array and things like `list(ts.diversity())` doesn't work for 0-d array). I won't be surprised if there's some good reason not to change this behavior, but if  changing `np.array(1.5)` to `1.5` won't cause problems then I'm for it.

**Comment by jeromekelleher** [comment]
Looking into the documentation for numpy [scalars](https://numpy.org/doc/stable/reference/arrays.scalars.html) there's no obvious reason to me why we couldn't do this.

I guess a first pass would be to try it out and see how much of our test suite it breaks?

**Comment by gtsambos** [comment]
Cool! Happy to do this, but it will have to wait until after June.
