### ISSUE TITLE
Global state style for svg/html drawing methods

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2362]
It would be handy for notebooks and jupyterbooks to be able to set a style for `tskit` generated SVG and HTML in a given session. A method such as `tskit.set_svg_style(css_string)` this global state would be used if no style was specified for `draw_svg` class.

**Comment by hyanwong** [comment]
Jupyter notebooks are weird because any style defined anywhere in the notebook percolates to the rest of the book (this doesn't happen in Jupyterbooks because the HTML and SVG elements are served as separate files, I think). So you may have to define unique IDs or classes for HTML and SVG elements to get exactly the style you expect.

**Comment by benjeffery** [comment]
No longer needed.
