### ISSUE TITLE
Change VCF sample IDs to ``tsk_{individual_id}``?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2445]
As noted in #2443, it would probably make more sense if our VCF sample IDs were of the form ``f"tsk_{ind_id}"`` rather than ``f"tsk_{j}``, where ``j`` is the position in the list of individual IDs.

However, this is a breaking change and I'm guessing would actually break people's code downstream. It's fine to change for standard msprime simulations (since the output will be the same), but I'm guessing that won't necessarily be true for forward simulations (or tsinfer'd trees, etc). People will almost certainly be hard-coding strings in downstream analysis code, so we'd break all that.

So my take would be that this is unfortunate, but not worth breaking people's code over and just something we should document clearly.

_Originally posted by @benjeffery in https://github.com/tskit-dev/tskit/pull/2443#discussion_r932065513_

**Comment by jeromekelleher** [comment]
I guess this would only be a breaking change if people used the ``individuals=[...]`` form, since the default parameters version would fail (or be wrong) on anything other than a tree sequence with exactly n individuals corresponding to the samples. So, worth thinking through, I guess.

**Comment by jeromekelleher** [comment]
But, then if we fix the code such we can deal properly with datasets that contain more complex sets of individuals (in #2443) we're potentially creating more breakage later if/when we change the default labelling scheme.

Any thoughts here @petrelharp, @bhaller?

**Comment by bhaller** [comment]
The way SLiM does it is described in section 26.2.3 of the SLiM manual, but basically, given a set of genomes, we just number them 1..N and call the samples i1..iN.  We don't try to do anything fancier with the sample IDs because the user can output any vector of genomes as VCF; in other words, the pair of genomes A,B in a given sample in the VCF file might not actually belong to the same diploid individual – they might be two unrelated haploid individuals, or they might be two haploid genomes taken from two different diploid individuals.

So to help people figure out what the file actually contains, we provide a separate line in the header:

`##slimGenomePedigreeIDs=4999898,4999899,...`

This is a list of the "genome pedigree IDs" for every haploid sample in the VCF file; in other words, the first diploid call line in the VCF file will be composed of calls for genome pedigree IDs 4999898 and 4999899, whether those were in the same individual or not.  Those genome pedigree IDs can then be translated into "individual pedigree IDs" (divide by two and round down), which can tell you whether they belong to the same individual or not; and by a happy non-coincidence, they also correspond to the tskit node IDs.

So, it's kinda gross, but that's how we do it.  I have no particular opinion as to how you guys ought to do it, or whether it's worth a breaking change or not.  I would note that you could add a mapping line to the header, like we do, to provide this information without it being a breaking change, since the sample IDs themselves could then remain unchanged.

**Comment by jeromekelleher** [comment]
Aha, excellent point @bhaller! We can give information about the samples in the header without needing a breaking change. We just stick with the convention now that we always have ``tsk_0``, ``tsk_``, etc and provide information about their individuals and node IDs in the header.

I'll open another issue to track that and clarify the docs to be clear on what we do.

Super helpful, thanks Ben!
