### ISSUE TITLE
A simplify method for Tree

### ISSUE THREAD

**Issue by sunyatin** [tskit-dev/tskit#2660]
Dear all,

First and foremost: a big thank you for this library which is both incredibly useful and elegant...

I had a small question about a fast way in tskit to **subsample a Tree to specific sample nodes**. I know we can do this with `ts.simplify(samples = [...])` but I would really like to perform the subsampling on a Tree rather than a TreeSequence. Is a Graph conversion the only way to do this?

Thank you very much!

Best,
Rémi

**Comment by jeromekelleher** [comment]
Hi @sunyatin, welcome :wave:

I can think of a few ways of doing this, but it would be helpful to understand why the straightforward approach below doesn't work for you:
 
```python
tss = ts.simplify(smaples=samples_your_interested_in)
tree = ts.at(position_youre_interested_in)
```

Can you give some detail on what you want to use this tree for?

**Comment by sunyatin** [comment]
Sure! Thank you Jerome for your answer. I want to calculate several tree-related statistics (coalescent times, Tk...) for several populations independently. So far, I have used the strategy:

```
tss = ts.simplify(samples = samples_in_pop_1)
for tree in tss.trees():
    [...]
    
tss = ts.simplify(samples = samples_in_pop_2)
for tree in tss.trees():
    [...]
    
etc.
```

but this is a bit inelegant, as I am iterating over the TreeSequence `npop` times. Instead, I would like to call the `ts.trees()`  just once, and do the subsampling within each iteration :)

**Comment by jeromekelleher** [comment]
What's your number of populations and number of trees? If the number of pops is (say) O(10) and number of trees is O(10^6) then calling simplify 10^6 times will be quite slow.

The ``for tree in tss.trees()`` loop is *very* fast, and there are ways of structuring many statistics so that they are computed quickly based on the differences between trees. (This [paper](https://academic.oup.com/genetics/article/215/3/779/5930459) is the best reference for incremental calculations, but we can dig out some more if you're interested)

Some of the stats you're interested in may be computable directly using the [stats api](https://tskit.dev/tskit/docs/stable/stats.html) without needing to simplify at all - you may be able to pass the population samples through in the list of sample sets. This [tutorial](https://tskit.dev/tutorials/analysing_tree_sequences.html) is a good place to start.

So, essentially, I wouldn't worry about iterating over the trees ``npop`` times :smile:

**Comment by sunyatin** [comment]
Great! Your estimations for npop and ntrees are very close to what I have (deviner!). I'll go for the multiple tree iterations then :) Will read this paper I did not know. Thank you Jerome!

**Comment by benjeffery** [comment]
Closing this as it seems resolved.
