### ISSUE TITLE
Mutation stack policy with add_mutation and "SLiM-style" mutation

### ISSUE THREAD

**Issue by romieuj** [tskit-dev/tskit#2733]
Hello,
I run introgression simulations using a combination of forward (SLiM) and backward (msprime) approaches.

For that I use SLiM to simulate the appearance of advantageous mutations then I add the neutral mutations in the sequence tree with msprime (msprime.sim_mutations()), I use the mutation model "SLiMMutationModel". 

I changed the mutation stack policy in SLiM, only the last mutation that appears at a given site is kept (mutationStackPolicy = "f"). The problem is that I don't have the impression that you can also change the stack policy for adding "SLiM-style" neutral mutations in msprime. But I would like that the advantageous mutations added in SLiM and those added afterwards by msprime "behave" in the same way and that only the last one appeared is retained, do you have a solution ? 

Thank you for taking the time to read my request,

Have a nice day,

Jules Romieu

**Comment by petrelharp** [comment]
Hello! The short answer is "no"; dealing with this would be nice but also daunting. One issue is that it's not entirely clear what we would actually want to happen: for instance, suppose that we have the stacking policy you say, that only the last mutation affects things. Then if you have both selected and neutral mutations in the SLiM simulation, a neutral mutation will "overwrite" the selected mutation and thus be, effectively, non-neutral. So, if you want 'neutral' mutations to be able to displace selected mutations, then adding mutations afterwards with msprime is *not* equivalent to having put them down in SLiM. The default stacking policy is the policy under which it is equivalent; and that's why we've stuck with that stacking policy in msprime.

However, it would be reasonable to have a "last" stacking policy in msprime if you *only* have netural mutations. Hm, in fact, we've got #2113 open on this topic.

I'm curious what, exactly, you'd like to do. Whatever it is, you can do it by manipulating mutations using pyslim; an example is here: https://tskit.dev/pyslim/docs/latest/vignette_coalescent_diversity.html

**Comment by romieuj** [comment]
Hello,
First of all, please excuse my delay in responding. 
Thank you very much for your answer. Indeed I had not thought of this problem if it is a neutral mutation that replaces an advantageous mutation. But somehow I think it is a false problem because it is biologically possible that a neutral mutation replaces an advantageous mutation at a given locus. This will have an impact on the fitness of the individual that will have a lower probability to reproduce than the individuals still carrying the advantageous mutation at this locus. In any case I imagine that this is how it would happen if we had both types of mutations in SLiM with the stack policy equal to "last". I'm a little less sure about what would happen if I added this parameter to sim_mutations() in msprime...

For the record, what I want to do is simulate an adaptive introgression event with SLiM. The advantageous mutations appear during the generations thanks to an advantageous mutation rate. Unfortunately I have problems with the so-called infinite population fitness of SLiM with this method of adding mutations. This problem is due to the fact that migration between subpopulations is only allowed at a given generation, so mutations can't be fixed in the total population and always count in the fitness calculation.  To overcome this problem I decided to change the stack policy and took other measures. 
I wanted the stack of neutral mutations added by msprime to behave the same way. 

Unfortunately my changes in SLiM did not completely solve the infinite fitness population problem so I will try to switch to a nucleotide based model (initializeSLiMOptions(nucleotideBased=T)). 

But I don't know if it is possible to simulate a diversity with msprime in a nucleotide-based model so that the tree sequence obtained can be used in slim with sim.readFromPopulationFile() ? 

In any case, thank you very much for your answer.

Have a nice day,

Jules

**Comment by petrelharp** [comment]
>  I'm a little less sure about what would happen if I added this parameter to sim_mutations() in msprime...

If the 'neutral' mutations that replaced selected mutations were added with msprime, it would be abiological - the mutations would no longer be consistent with the genealogical relationships.

> I don't know if it is possible to simulate a diversity with msprime in a nucleotide-based model so that the tree sequence obtained can be used in slim with sim.readFromPopulationFile() ?

It is possible! This sort of thing (although not that exact thing) is demonstrated in the pyslim documentation.

I've thought about this topic a good bit, and as far as I can see your options are:
1. Lay down neutral mutations in msprime that 'stack', even though the selected mutations in SLiM don't stack. This is a bit odd, but the practical difference should be very small.
2. Generate all mutations in SLiM, none in msprime. This will be slower, but less confusing.
3. Generate neutral mutations in SLiM but then either remove or don't put down in the first place neutral mutations at any sites having selected mutations. 
4. Get the mutations added by msprime to replace previous mutations, and ignore the fact that the genotypes aren't quite consistent with the genealogical history. This is I think the worst way, as it might even be actively misleading (but it's maybe a valid approximation to reality?).

I'd go for option (1). Maybe option (3) is the best if you really need something like just-a-single-nucleotide-at-each-site.

I'll close this issue (since I think we resolved the original question?); feel free to re-open if it's not resolved? I think if you are running into issues editing mutations, eg to add nucleotides or selection coefficients to an msprime simulation, you should open an issue on pyslim, which deals with the slim-interface.
