### ISSUE TITLE
draw_svg y_ticks doc issues and unexpected behaviour

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2990]
Currently says

> y_ticks (list) – A list of Y values at which to plot tickmarks ([] gives no tickmarks). If None, plot one tickmark for each unique node value.

Should be a mapping of value to labels, right? Passing in a list gives no labels.

**Comment by jeromekelleher** [comment]
Hmm, there's some other unexpected stuff happening here. This is what I get when I try to pass a mapping:
![Screenshot from 2024-09-24 11-00-12](https://github.com/user-attachments/assets/70c1aa1f-33d4-40b6-a601-62673e3b5589)

This is what we get when y_ticks is None:
![Screenshot from 2024-09-24 11-00-48](https://github.com/user-attachments/assets/fa6d80b4-e9fc-4828-9aca-82895e0f85cf)

**Comment by hyanwong** [comment]
We document that it is a list, but there is a (currently undocumented) addition that it can be a mapping, if you want to change the labels.

I think the behaviour in the examples above is correct, because you are using `time_scale="rank"`, and so the Y axis times are not evenly spaced. In the second case, there are lots of times that are roughly at t=225, and you are simply loosing resolution in the number of decimal places seen.

In the first case, the routine expected a mapping of rank index (not time) to labels. We should document this. I guess it would be nicer to map times (rather than ranks) to labels where possible, but it's probably a bit fiddly to interpolate to times that are between the ranks, so maybe easier just to document the current behaviour, rather than add a load more logic to the drawing routines?

**Comment by hyanwong** [comment]
NB: a simple example of providing a list is at https://tskit.dev/tutorials/viz.html#larger-tree-sequences

**Comment by hyanwong** [comment]
I guess the simplest fix is to change the docstring for the parameter description to read something like:
    :param  Union[list, dict] y_ticks: A list of Y values at which to plot
            tickmarks, or a dictionary mapping values to labels (``[]``
            gives no tickmarks). If ``None``, plot one tickmark for each unique
            node value. Note that if ``time_scale="rank"``, the Y values should
            correspond to the integer rank of the plotted nodes. Default: None.

Does that sound right, @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Ah I see, that's very helpful. Updating the documentation to be more precise helps here as it's not very clear what's going on in the rank case.

It would also help if we generated a warning when tick labels are provided that fall off the plotted area - it wasn't at all obvious what was happening here.

**Comment by jeromekelleher** [comment]
What I want to do here FWIW is to transform the time-ago values on the y-axis into dates, which I'd imagine isn't that obscure

**Comment by hyanwong** [comment]
A warning is a good idea.

Re obscurity or otherwise, it's not clear to me where to place an "intermediate" value if the time scale is ranked. E.g. if the node ranks are at 1st Dec 2020, 2nd Dec 2020, and 30th Dec 2020, which are placed at Y positions 0, 1, and 2, where do we put a tick for 3rd Dec 2020? I guess we simply linearly interpolate between 1 and 2, so put it at rank position `1 + (1/28)`, but you could imagine other options too.

In the example you gave above, `{225: '2020-07-28', 226: '2020-07-29'}` might lead to a bit of a misleading scale if there are lots of extra unlabelled ranks at times 225.00001, 225.00002, 225.00008, etc. so I'm not sure it's quite as simple as all that.

**Comment by jeromekelleher** [comment]
I don't think we'd need to support interpoloating ranks, could just error.
