### ISSUE TITLE
Iterator over parents of a node in a tree

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#360]
A few times now I have wanted to traverse up a tree from a given node, visiting all the parents (in any order, as it happens). I can presumably do this like:

```
def parents(tree, node):
    while node != tskit.NULL:
        node = tree.parent(node)
        yield node
```

But I'm wondering if (a) there is a more efficient (numpy) way to do this and (b) if we want to provide a python API function so that others don't have to re-write this each time. Ping @awohns, since I think his dating code may use this sort of functionality for efficient stats calculations.  I suspect it's the sort of thing that efficient incremental stats calculations are based on, so might be of general interest.

**Comment by petrelharp** [comment]
Hah, I was just now doing this, [right here](https://github.com/petrelharp/big_small/blob/14c8d00e71782b4e16b67117c8ebde7025bb1ea4/sims/spatial_slim/__init__.py#L68), and it was taking a long time to do, so I was wishing there was a faster way to do it.

So, there's two issues: one is making a python interface so that people don't have to write the three lines above themselves. I actually don't think we need to do that - the above is very concise already. 

But, the thing that I think would be maybe useful extracting stuff obtained along that traversal. We could, say, provide a function `ts.lineages(samples, position)` that returns a list of length equal to `len(samples)` whose `k`th element is the numpy array of nodes that are obtained in the traversal up from `samples[k]` at `position`. We could then do efficient numpy things with these.

**Comment by jeromekelleher** [comment]
> So, there's two issues: one is making a python interface so that people don't have to write the three lines above themselves. I actually don't think we need to do that - the above is very concise already.

Agreed --- we're not going to be able to do it any more efficiently anyway unless we do it in C.

> But, the thing that I think would be maybe useful extracting stuff obtained along that traversal. We could, say, provide a function ts.lineages(samples, position) that returns a list of length equal to len(samples) whose kth element is the numpy array of nodes that are obtained in the traversal up from samples[k] at position. We could then do efficient numpy things with these.

This is going to be tricky to do, as numpy doesn't do ragged arrays very well. I don't think we're going to make anyone's code faster with an interface like this to be honest --- at some point you end up just having to do stuff with loops. We'd be better off putting effort into making sure that things like Cython and numba can make efficient code that does tree traversals.  **However**, this is a non-trivial task which we absolutely don't have developer bandwidth for right now.

Re @awohns code, we'd be better off writing a full C version of the algorithm --- it'll be a lot simpler. 

I'm going to close this for now; feel free to reopen if there's something specific to take up.
