### ISSUE TITLE
write_vcf() should have isolated_as_missing option

### ISSUE THREAD

**Issue by brianzhang01** [tskit-dev/tskit#447]
I am working with a tree sequence that someone else created using SLiM. When trying to read in the tree sequence (using tskit.load) and write out VCF using the write_vcf() function, I get the error
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/users/marchini/bzhang/.local/lib/python3.6/site-packages/tskit/trees.py", line 3039, in write_vcf
    writer.write(output)
  File "/users/marchini/bzhang/.local/lib/python3.6/site-packages/tskit/vcf.py", line 156, in write
    for variant in self.tree_sequence.variants(samples=self.samples):
  File "/users/marchini/bzhang/.local/lib/python3.6/site-packages/tskit/trees.py", line 2774, in variants
    impute_missing_data=impute_missing_data)
_tskit.LibraryError: Cannot generate genotypes for non-samples unless missing data imputation is enabled
```

I get a similar traceback when I try to create a VCF file from this tree sequence using the command-line interface: `tskit vcf tmp.trees`. I presume this is due to missing data in the tree sequence, and it seems like several other methods have an impute_missing_data option -- should this be added to write_vcf?

I'm aware that for SLiM tree sequences, pyslim may be the more appropriate package -- I'm starting to look into those docs now.

**Comment by petrelharp** [comment]
Ah, I know the problem here - a SLiM-produced tree sequence has individuals whose nodes are not marked as "samples"; but then by default `write_vcf`, if there are individuals present, will try to write out a VCF of all individuals; thus leading to this error. The error is sort of wrong, in this case - even though those individuals have nodes not marked as samples, we've got entire data on them, so there is no missing data  to be imputed.

So, probably what you want to do is
```
ts = pyslim.load("file.trees")
ts.write_vcf(ts.individuals_alive_at(0))
```
(the `individuals_alive_at( )` function is provided by pyslim). This will write out a VCF of everyone alive today (ie the end of the simulation).

Things we might do about this:
- Perhaps we should change the default for `write_vcf( )` to write for all individuals *whose nodes are samples*?
- Or - and probably better - we could actually output 'missing' genotypes to the VCF (with `.` or `N`).
-  Separately, we might also write a pyslim version of write_vcf that has more sensible SLiM-related options.

**Comment by jeromekelleher** [comment]
Asides from the pyslim subtleties, I guess the ``write_vcf`` output really should have methods to deal with missing data. I think "." is the accepted format for this, and it should be easy to implement so I've added it to the next release milestone.
