### ISSUE TITLE
Tree-sequence-level metadata

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#534]
As discussed in #491 it would be useful to have top-level metadata, using the same schema and encodings as row-level metadata. #491 is already a large PR so this will be done separately.

**Comment by hyanwong** [comment]
By the way, would we ever want *tree*-specific metadata @benjeffery ? There's really no place for this. We would need a separate "tree" table.

**Comment by jeromekelleher** [comment]
We'd need a clear and compelling justification for this - everything is fundamentally built around the idea that individual trees aren't important, it's the nodes and edges.

**Comment by hyanwong** [comment]
Yes, I generally agree. The recent foray into BEAST trees (thanks a *lot* for looking into this @jeromekelleher) was my initial thought for this, but since that didn't really pan out, I can't think of any immediate justification at the moment, other than people are used to annotating specific trees with additional information. In general I agree that we should force them to think otherwise, though

**Comment by hyanwong** [comment]
For easy reference, the discussion in https://github.com/tskit-dev/tskit/issues/495 details some of the uses of ts-level metadata, and some discussion of how we might want it to work.

**Comment by benjeffery** [comment]
Once #534 is complete, if the user really wanted per-tree metadata it could be stored as an array in the tree-sequence metadata. As this is not a common use-case I think that should suffice.

**Comment by jeromekelleher** [comment]
Good call @benjeffery, that's a very pragmatic idea.
