### ISSUE TITLE
Add ``total_bytes`` attribute to Table objects

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#54]
It'll be useful to be able to track the actual size in bytes of tables. Add an attribute to return the total amount of memory consumed by each table.

**Comment by brianzhang01** [comment]
I'm currently trying to get out the memory of my tree sequences. From Python I'm using [pympler's](https://pythonhosted.org/Pympler/) asizeof function, but this seems to only catch the Python wrapping part, not the underlying C structures. I think this functionality could fulfill my use case.

**Comment by jeromekelleher** [comment]
Good to know @brianzhang01 - I think it's a straightforward thing to add, and it'll get done quicker if you'd like to help out :wink:

I'm not sure it'd help much for the issue you're having with tracking the memory left behind after tree sequences though - this is just for the TableCollection objects. It'd be too much work to keep track of all the memory used for a TreeSequence.

**Comment by jeromekelleher** [comment]
So, if we just wanted to get the memory directly used by the columns, we could do this in Python by summing the ``nbytes`` of all the column arrays. This wouldn't be exactly right, because the tables will sometimes have a bit more memory allocated as buffer space for adding extra rows. But it's probably good enough for most purposes.

**Comment by brianzhang01** [comment]
I see. In terms of tracking total memory used from Python, it seems like `pympler` is too small since it only seems to look at Python wrapping. `psutil` gives what I'm most interested in -- the total memory consumed by the process -- but that's over the whole Python script, and it also catches memory used by "free lists" (#732 ). I'm interested in all the C memory consumption, which also seems different than this issue due to memory outside the TableCollections.

I don't work much with the C API so I would rather not work on this for now.
