### ISSUE TITLE
Minlex ordering means node label positioning no longer correct

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#615]
As we decide which side of a branch or node to put the label using `tree.left_sib(u)` (https://github.com/tskit-dev/tskit/blob/bbb020fcebc7fd00a700cd55b55ba8d2c4c8ec04/python/tskit/drawing.py#L626) which no longer always agrees with the minlex ordering.

**Comment by jeromekelleher** [comment]
Ah. Probably the simplest thing to do is make a `get_left_sib`` method like this one [here](https://github.com/tskit-dev/tskit/blob/bbb020fcebc7fd00a700cd55b55ba8d2c4c8ec04/python/tskit/drawing.py#L737). This will be easier, as it can be done in a single pass through the nodes under the defined ordering.

So, instead of calling ``tree.left_sib(mutation_node) == NULL`` we'd call ``left_sib[mutation.node]`` or suchlike.

**Comment by jeromekelleher** [comment]
Are you happy to pick this one up @hyanwong?

**Comment by hyanwong** [comment]
Yep. I can do this.
