### ISSUE TITLE
Function for converting Newick tree to tree sequence

### ISSUE THREAD

**Issue by winni2k** [tskit-dev/tskit#793]
For better or for worse, the world is full of Newick formatted trees. What is the recommended way of converting a Newick tree to a tree sequence?

**Comment by gbinux** [comment]
I think this is a very interesting problem. Newick format trees can be parsed line by line. Each line is a marginal tree and two contiguous lines/trees share a lot info. Newick format record the tree topology and the branch length (instead of  the height or time of each node). When summarizing the branch lengths to calculate time of nodes, there could be inaccuracy due to limit precisions; calculation via different paths may generate different result for node time. Time is important for the uniqueness of internal nodes of Tree sequence format. I think converting newick tree to tree sequence can be done if every internal node in each newick tree has unique time and one marginal tree only has one different node than the previous tree. Once the conditions are satisfied, algorithm can be designed to find the different node and edges between the two adjacent trees and add the different nodes and edges to  the internal table collection in the tree sequence format.  Walking along the marginal tree from left hand side of the chromosome to the right hand side, node/edge tables of tree sequence can be completed. Many of the details are described this two papers:

1. PLOS Computational Biology. 2016. 10.1371/journal.pcbi.1004842

2. PLOS Computational Biology. 2018. 10.1371/journal.pcbi.1006581

**Comment by jeromekelleher** [comment]
Thanks @gbinux, that's a great summary!

FWIW, there's a method to convert newick trees in ms format in [tsconvert](https://github.com/tskit-dev/tsconvert/blob/master/tsconvert/newick.py). It works pretty well, but makes a pretty hard assumption about the uniqueness of node times. I went off on a digression about parsing BEAST trees at some point fairly recently too, which I can dig up if you're interested @winni2k  - the conclusion was that there wasn't much point, though.

If you just want to convert a single newick tree, then it's pretty straightforward. It's not something I foresee being a part of tskit because we'd need a dependency to parse newick, but it's a possibility.

**Comment by winni2k** [comment]
I think I remember the conversation around the parsing of beast output now that you mention it.

I guess I am having an xy problem. I created a tree using msprime and tried to infer it using some beast-like tools. Now I want to evaluate how well I did on Robinson folks distance and some clustering accuracy metrics and I find myself trying to figure out how to get all the trees into the same format and what library to use for the comparisons. Given that conversion of beast output to tree sequence is not implemented, I thought of using ape in r, or networkx in python. Is there an r library for parsing tree sequences? Is there a good python library for working with phylogenetic trees? I am using ete3 for rf distance, but I didn't see the other metrics implemented.

**Comment by winni2k** [comment]
Also, I'll try tsconvert.

**Comment by jeromekelleher** [comment]
It's a mixed bag for phylo stuff in Python I think, the R packages are much better AFAIK.

There's no "tskitR", but it could exist some day!

Also, rather than RF distance you could use the Kendall Colijn metric in [tskit](https://tskit.readthedocs.io/en/latest/python-api.html#tskit.Tree.kc_distance). It's much better than RF in a bunch of ways, I think it's totally defensible to use it and not bother with RF and all the other ones.

**Comment by grahamgower** [comment]
I have some dumb implementations for RF-like distances for tree sequences, if that is of interest.

**Comment by winni2k** [comment]
Thanks for the paper link @jeromekelleher! It sounds like I would be best advised to perform my analyses in R, and to convert my tree sequences to Newick files for that. It appears there exist at least two R implementations of KC distance (https://cran.r-project.org/web/packages/treespace/vignettes/introduction.html, https://rdrr.io/cran/TreeDist/src/R/tree_distance_kendall-colijn.R). 

Thank you everyone for your comments. You have more than answered my questions.
