### ISSUE TITLE
Output Newick without branch lengths

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#914]
A trivial thing, but it would be useful for me to [output a Newick tree](https://tskit.readthedocs.io/en/latest/_modules/tskit/trees.html#Tree.newick) (or indeed a set of nexus trees) without branch lengths. I wonder if that's a useful thing to do if `precision=None`? Or if that's a bit too cryptic, and overriding the normal use of None as a marker for the default value of a parameter?

**Comment by jeromekelleher** [comment]
I'd slightly worry about using None in a way that's not "use the default value" here. What about having a negative precision meaning "don't print out branch lengths"? It sort of makes sense.

The only other option is to add another parameter ``branch_lengths=True``. This is perhaps a bit more extensible, since we might want to add other stuff into the newick in the future (like, say, metadata encoded as extended newick) and precision might apply across a number of different things, not just branch lengths.

Either way, I wouldn't bother implementing in the C engine.

**Comment by hyanwong** [comment]
> I'd slightly worry about using None in a way that's not "use the default value" here.

Yes, I thought that too.

> What about having a negative precision meaning "don't print out branch lengths"? It sort of makes sense.

I guess there's no other meaning. We could make it a bit more intuitive to the reader by recommending the use of `tskit.NULL`
 
> The only other option is to add another parameter `branch_lengths=True`. This is perhaps a bit more extensible, since we might want to add other stuff into the newick in the future (like, say, metadata encoded as extended newick) and precision might apply across a number of different things, not just branch lengths.

Whatever you think best.

> Either way, I wouldn't bother implementing in the C engine.

Agreed.

**Comment by jeromekelleher** [comment]
Probably simplest to add a new parameter, ``branch_lenghths=True``. It's the least cryptic and most discoverable.

**Comment by hyanwong** [comment]
Fixed in https://github.com/tskit-dev/tskit/pull/931
