### ISSUE TITLE
tsk_tree_copy(...) does not copy value of tsk_tree_t.mark

### ISSUE THREAD

**Issue by castedo** [tskit-dev/tskit#925]
I noticed in `tskit/trees.c` that https://github.com/tskit-dev/tskit/blob/f1c5e29e2f4ed022a436895cea3e92f21e368ec6/c/tskit/trees.c#L3329

does not copy the value of https://github.com/tskit-dev/tskit/blob/f1c5e29e2f4ed022a436895cea3e92f21e368ec6/c/tskit/trees.h#L176 from `self` to `dest`. The unit test for `tree_tree_copy` does not check for `mark` getting copied.

Shouldn't `mark` get copied?

**Comment by jeromekelleher** [comment]
I think ``mark`` will get removed at some point - as far as I know, it's only used in the ``ld_calculator`` and we'll be rewriting/generalising this "soon" as part of the generalised two-site statistics (https://github.com/tskit-dev/tskit/projects/1)

Whether we should update it is debateable - I'm inclined not to, since things are currently working and it's scheduled for removal. We should document it as such in the code though, to avoid confusion.

**Comment by jeromekelleher** [comment]
Added to C API 1.0 - we should clear this cruft out, if we can at all.

**Comment by jeromekelleher** [comment]
This is an undocumented feature of the tree, and will be removed (or generalised) at some point in the future.
