### ISSUE TITLE
Flakey test "TestNodeTraitRegression.test_wright_fisher_unsimplified"

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#988]
I've seen this test fail on CI at a rate of a couple a week.
```
 =================================== FAILURES ===================================
 ___________ TestNodeTraitRegression.test_wright_fisher_unsimplified ____________
 [gw1] darwin -- Python 3.6.11 /usr/local/miniconda/envs/anaconda-client-env/bin/python3.6
 
 self = <tests.test_tree_stats.TestNodeTraitRegression object at 0x7fe6c4bda048>
 
     def test_wright_fisher_unsimplified(self):
         tables = wf.wf_sim(
             4,
             5,
             seed=1,
             deep_history=True,
             initial_generation_samples=False,
             num_loci=5,
         )
         tables.sort()
         ts = tables.tree_sequence()
 >       self.verify(ts)
 
 tests/test_tree_stats.py:594: 
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
 tests/test_tree_stats.py:4488: in verify
     self.verify_trait_regression(ts, W, Z, windows=windows)
 tests/test_tree_stats.py:4546: in verify_trait_regression
     self.assertArrayAlmostEqual(sigma1, sigma3)
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
 
 self = <tests.test_tree_stats.TestNodeTraitRegression object at 0x7fe6c4bda048>
 x = array([[[0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         ...65014],
         [0.        ],
         [0.2617744 ],
         [0.        ],
         [0.        ],
         [0.19294995]]])
 y = array([[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
       ...[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]])
 atol = 1e-06, rtol = 1e-07
 
     def assertArrayAlmostEqual(self, x, y, atol=1e-6, rtol=1e-7):
 >       nt.assert_allclose(x, y, atol=atol, rtol=rtol)
 E       AssertionError: 
 E       Not equal to tolerance rtol=1e-07, atol=1e-06
 E       
 E       Mismatched elements: 103 / 315 (32.7%)
 E       Max absolute difference: 0.26177442
 E       Max relative difference: inf
 E        x: array([[[0.      ],
 E               [0.      ],
 E               [0.      ],...
 E        y: array([[[0.],
 E               [0.],
 E               [0.],...
 
 tests/test_tree_stats.py:541: AssertionError
```

**Comment by jeromekelleher** [comment]
I'm sure this is probably just because there isn't enough data or something in some particular replicate. We should just fix the random seed.

**Comment by benjeffery** [comment]
Which seed? The seed to `wf_sim` is fixed.

**Comment by jeromekelleher** [comment]
Oh yeah, so it is. Hmm - could be that wf_sim isn't actually using the seed properly.

**Comment by benjeffery** [comment]
Looking though `wf_sim` it seems to be legit. I'm running the test locally, no failures yet.

**Comment by benjeffery** [comment]
Run several hundred times without error locally. Failure on CI is OSX, not that that should matter.

**Comment by petrelharp** [comment]
wow, well, this is weird.

**Comment by benjeffery** [comment]
It might be co-incidental, but this has only started happening since we switched to parallel test execution. I don't see how this could change things though as that is multi-process.

**Comment by petrelharp** [comment]
Ok, so here's the problem, I'm 99% sure: https://github.com/tskit-dev/tskit/blob/main/c/tskit/trees.c#L2554

What's happening (I think) is that occasionally by chance the [trait values](https://github.com/tskit-dev/tskit/blob/main/python/tests/test_tree_stats.py#L938) are almost in the linear span of the [covariates](https://github.com/tskit-dev/tskit/blob/main/python/tests/test_tree_stats.py#L4457), resulting in an answer of 0.0, basically due to numerical issues. I don't know why this would happen more often on some systems than other ones?

I suppose this is happening unpredictably because I didn't adequately insert a random seed into the places that generate traits and covariates? 

I should have picked up on this earlier, but seeing two different results where one was all 0.0's made me remember this issue. (so, thanks @benjeffery)

And to totally fix it I guess I should modify the python version to replicate the same numerical test.

**Comment by benjeffery** [comment]
Glad you remembered this as I didn't really know where to start! Setting the seed for those random functions should do the job. Phew!
